FROM node:23-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install

RUN npm i -g serve

COPY . .

ENV VITE_INSTANCE_ID=$VITE_INSTANCE_ID_BUILD
ENV VITE_API_URL=$VITE_API_URL_BUILD

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist", "-l", "3000" ]
