spring:
  application:
    name: locadoraapi
  datasource:
    url: jdbc:postgresql://localhost:5432/locadora
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create,none, create-drope